export interface Product {
  id: string;
  name: string;
  category: 'clothing' | 'accessories' | 'jewelry' | 'shoes' | 'underwear';
  subcategory: string;
  gender: 'men' | 'women' | 'unisex';
  price: number;
  description: string;
  colors: string[];
  sizes: string[];
  inStock: boolean;
  images?: string[];
  tags: string[];
}

// Примерная база товаров (в реальном проекте это будет подключение к БД)
export const PRODUCT_DATABASE: Product[] = [
  // Женская одежда
  {
    id: 'w_dress_001',
    name: 'Элегантное черное платье',
    category: 'clothing',
    subcategory: 'dress',
    gender: 'women',
    price: 4500,
    description:
      'Классическое черное платье из качественного трикотажа. Идеально для офиса и вечерних мероприятий.',
    colors: ['черный', 'темно-синий'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tags: ['элегантное', 'офисное', 'вечернее', 'классика'],
  },
  {
    id: 'w_blouse_001',
    name: 'Шелковая блузка',
    category: 'clothing',
    subcategory: 'blouse',
    gender: 'women',
    price: 3200,
    description: 'Роскошная блузка из натурального шелка с изящным кроем.',
    colors: ['белый', 'кремовый', 'пудровый'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tags: ['шелк', 'роскошь', 'офисная', 'праздничная'],
  },
  {
    id: 'w_jeans_001',
    name: 'Джинсы скинни',
    category: 'clothing',
    subcategory: 'jeans',
    gender: 'women',
    price: 2800,
    description: 'Стильные джинсы скинни из premium denim с высокой посадкой.',
    colors: ['темно-синий', 'черный', 'серый'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tags: ['джинсы', 'скинни', 'повседневное', 'стильные'],
  },
  {
    id: 'w_dress_002',
    name: 'Летнее платье с цветочным принтом',
    category: 'clothing',
    subcategory: 'dress',
    gender: 'women',
    price: 3800,
    description: 'Легкое летнее платье из натурального хлопка с романтичным цветочным принтом.',
    colors: ['голубой', 'розовый', 'белый'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tags: ['летнее', 'цветочный принт', 'романтичное', 'хлопок'],
  },
  {
    id: 'w_skirt_001',
    name: 'Плиссированная юбка',
    category: 'clothing',
    subcategory: 'skirt',
    gender: 'women',
    price: 2400,
    description: 'Элегантная плиссированная юбка миди длины из качественной ткани.',
    colors: ['черный', 'бежевый', 'темно-синий'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tags: ['плиссированная', 'миди', 'элегантная', 'офисная'],
  },
  {
    id: 'w_sweater_001',
    name: 'Кашемировый свитер',
    category: 'clothing',
    subcategory: 'sweater',
    gender: 'women',
    price: 5200,
    description: 'Роскошный свитер из 100% кашемира с V-образным вырезом.',
    colors: ['серый', 'бежевый', 'темно-синий', 'черный'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tags: ['кашемир', 'роскошный', 'V-вырез', 'теплый'],
  },
  {
    id: 'w_jacket_001',
    name: 'Кожаная куртка',
    category: 'clothing',
    subcategory: 'jacket',
    gender: 'women',
    price: 12500,
    description: 'Стильная куртка из натуральной кожи в байкерском стиле.',
    colors: ['черный', 'коричневый'],
    sizes: ['XS', 'S', 'M', 'L'],
    inStock: true,
    tags: ['кожа', 'байкерский стиль', 'стильная', 'натуральная'],
  },
  {
    id: 'w_pants_001',
    name: 'Классические брюки',
    category: 'clothing',
    subcategory: 'pants',
    gender: 'women',
    price: 3600,
    description: 'Элегантные брюки прямого кроя для офиса и деловых встреч.',
    colors: ['черный', 'серый', 'темно-синий'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tags: ['классические', 'офисные', 'деловые', 'прямой крой'],
  },

  // Мужская одежда
  {
    id: 'm_shirt_001',
    name: 'Классическая рубашка',
    category: 'clothing',
    subcategory: 'shirt',
    gender: 'men',
    price: 2900,
    description: 'Элегантная мужская рубашка из хлопка премиум качества.',
    colors: ['белый', 'голубой', 'серый'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['классика', 'офисная', 'хлопок', 'элегантная'],
  },
  {
    id: 'm_jeans_001',
    name: 'Мужские джинсы прямого кроя',
    category: 'clothing',
    subcategory: 'jeans',
    gender: 'men',
    price: 3500,
    description: 'Комфортные джинсы прямого кроя из качественного денима.',
    colors: ['синий', 'черный', 'серый'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['джинсы', 'прямой крой', 'повседневные', 'комфорт'],
  },
  {
    id: 'm_tshirt_001',
    name: 'Хлопковая футболка',
    category: 'clothing',
    subcategory: 'tshirt',
    gender: 'men',
    price: 1800,
    description: 'Базовая футболка из 100% хлопка премиум качества.',
    colors: ['белый', 'черный', 'серый', 'темно-синий'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['хлопок', 'базовая', 'повседневная', 'комфорт'],
  },
  {
    id: 'm_sweater_001',
    name: 'Мужской свитер',
    category: 'clothing',
    subcategory: 'sweater',
    gender: 'men',
    price: 4200,
    description: 'Теплый свитер из шерсти мериноса с круглым вырезом.',
    colors: ['серый', 'темно-синий', 'черный', 'бордовый'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['шерсть мериноса', 'теплый', 'круглый вырез', 'зимний'],
  },
  {
    id: 'm_jacket_001',
    name: 'Деловой пиджак',
    category: 'clothing',
    subcategory: 'jacket',
    gender: 'men',
    price: 8900,
    description: 'Классический деловой пиджак из качественной шерсти.',
    colors: ['темно-синий', 'серый', 'черный'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['деловой', 'классический', 'шерсть', 'офисный'],
  },

  // Аксессуары
  {
    id: 'acc_bag_001',
    name: 'Кожаная сумка',
    category: 'accessories',
    subcategory: 'bag',
    gender: 'women',
    price: 8500,
    description: 'Элегантная сумка из натуральной кожи с золотистой фурнитурой.',
    colors: ['черный', 'коричневый', 'бежевый'],
    sizes: ['One Size'],
    inStock: true,
    tags: ['кожа', 'элегантная', 'золотистая фурнитура', 'натуральная'],
  },
  {
    id: 'acc_belt_001',
    name: 'Кожаный ремень',
    category: 'accessories',
    subcategory: 'belt',
    gender: 'men',
    price: 3200,
    description: 'Классический мужской ремень из качественной кожи.',
    colors: ['черный', 'коричневый'],
    sizes: ['85', '90', '95', '100', '105'],
    inStock: true,
    tags: ['кожа', 'классический', 'деловой', 'качественная'],
  },
  {
    id: 'acc_scarf_001',
    name: 'Шелковый платок',
    category: 'accessories',
    subcategory: 'scarf',
    gender: 'women',
    price: 2800,
    description: 'Роскошный шелковый платок с авторским принтом.',
    colors: ['синий', 'красный', 'зеленый', 'золотой'],
    sizes: ['One Size'],
    inStock: true,
    tags: ['шелк', 'роскошный', 'авторский принт', 'элегантный'],
  },
  {
    id: 'acc_hat_001',
    name: 'Фетровая шляпа',
    category: 'accessories',
    subcategory: 'hat',
    gender: 'unisex',
    price: 4200,
    description: 'Стильная фетровая шляпа классического кроя.',
    colors: ['черный', 'серый', 'коричневый'],
    sizes: ['S', 'M', 'L'],
    inStock: true,
    tags: ['фетр', 'стильная', 'классическая', 'унисекс'],
  },
  {
    id: 'acc_wallet_001',
    name: 'Кожаный кошелек',
    category: 'accessories',
    subcategory: 'wallet',
    gender: 'men',
    price: 2400,
    description: 'Компактный мужской кошелек из натуральной кожи.',
    colors: ['черный', 'коричневый'],
    sizes: ['One Size'],
    inStock: true,
    tags: ['кожа', 'компактный', 'натуральная', 'мужской'],
  },
  {
    id: 'acc_gloves_001',
    name: 'Кожаные перчатки',
    category: 'accessories',
    subcategory: 'gloves',
    gender: 'women',
    price: 3600,
    description: 'Элегантные женские перчатки из мягкой кожи.',
    colors: ['черный', 'коричневый', 'бежевый'],
    sizes: ['S', 'M', 'L'],
    inStock: true,
    tags: ['кожа', 'элегантные', 'мягкая', 'женские'],
  },

  // Ювелирные изделия
  {
    id: 'jewelry_necklace_001',
    name: 'Золотая цепочка',
    category: 'jewelry',
    subcategory: 'necklace',
    gender: 'women',
    price: 15000,
    description: 'Изящная золотая цепочка 585 пробы с подвеской.',
    colors: ['золотой'],
    sizes: ['45см', '50см', '55см'],
    inStock: true,
    tags: ['золото', '585 проба', 'подвеска', 'изящная'],
  },
  {
    id: 'jewelry_ring_001',
    name: 'Серебряное кольцо',
    category: 'jewelry',
    subcategory: 'ring',
    gender: 'unisex',
    price: 4500,
    description: 'Стильное серебряное кольцо с минималистичным дизайном.',
    colors: ['серебряный'],
    sizes: ['16', '17', '18', '19', '20'],
    inStock: true,
    tags: ['серебро', 'минималистичный', 'стильное', 'унисекс'],
  },
  {
    id: 'jewelry_earrings_001',
    name: 'Жемчужные серьги',
    category: 'jewelry',
    subcategory: 'earrings',
    gender: 'women',
    price: 8500,
    description: 'Классические серьги с натуральным жемчугом.',
    colors: ['белый', 'кремовый'],
    sizes: ['One Size'],
    inStock: true,
    tags: ['жемчуг', 'натуральный', 'классические', 'элегантные'],
  },
  {
    id: 'jewelry_bracelet_001',
    name: 'Золотой браслет',
    category: 'jewelry',
    subcategory: 'bracelet',
    gender: 'women',
    price: 12000,
    description: 'Роскошный золотой браслет с филигранной работой.',
    colors: ['золотой'],
    sizes: ['16см', '17см', '18см'],
    inStock: true,
    tags: ['золото', 'роскошный', 'филигрань', 'ручная работа'],
  },
  {
    id: 'jewelry_watch_001',
    name: 'Часы премиум класса',
    category: 'jewelry',
    subcategory: 'watch',
    gender: 'men',
    price: 25000,
    description: 'Швейцарские часы с механическим механизмом и кожаным ремешком.',
    colors: ['черный', 'коричневый'],
    sizes: ['One Size'],
    inStock: true,
    tags: ['швейцарские', 'механические', 'премиум', 'кожаный ремешок'],
  },

  // Обувь
  {
    id: 'shoes_w_heels_001',
    name: 'Классические туфли на каблуке',
    category: 'shoes',
    subcategory: 'heels',
    gender: 'women',
    price: 6800,
    description: 'Элегантные женские туфли на среднем каблуке из натуральной кожи.',
    colors: ['черный', 'бежевый', 'темно-синий'],
    sizes: ['36', '37', '38', '39', '40'],
    inStock: true,
    tags: ['туфли', 'каблук', 'натуральная кожа', 'элегантные'],
  },
  {
    id: 'shoes_w_flats_001',
    name: 'Балетки',
    category: 'shoes',
    subcategory: 'flats',
    gender: 'women',
    price: 3200,
    description: 'Комфортные балетки из мягкой кожи для повседневной носки.',
    colors: ['черный', 'бежевый', 'розовый', 'белый'],
    sizes: ['36', '37', '38', '39', '40'],
    inStock: true,
    tags: ['балетки', 'комфортные', 'мягкая кожа', 'повседневные'],
  },
  {
    id: 'shoes_w_boots_001',
    name: 'Высокие сапоги',
    category: 'shoes',
    subcategory: 'boots',
    gender: 'women',
    price: 9500,
    description: 'Стильные высокие сапоги из замши на устойчивом каблуке.',
    colors: ['черный', 'коричневый', 'серый'],
    sizes: ['36', '37', '38', '39', '40'],
    inStock: true,
    tags: ['сапоги', 'высокие', 'замша', 'устойчивый каблук'],
  },
  {
    id: 'shoes_w_sneakers_001',
    name: 'Женские кроссовки',
    category: 'shoes',
    subcategory: 'sneakers',
    gender: 'women',
    price: 4500,
    description: 'Удобные спортивные кроссовки для активного образа жизни.',
    colors: ['белый', 'черный', 'розовый', 'серый'],
    sizes: ['36', '37', '38', '39', '40'],
    inStock: true,
    tags: ['кроссовки', 'спортивные', 'удобные', 'активный образ жизни'],
  },
  {
    id: 'shoes_m_dress_001',
    name: 'Классические мужские туфли',
    category: 'shoes',
    subcategory: 'dress',
    gender: 'men',
    price: 8900,
    description: 'Элегантные мужские туфли из натуральной кожи для деловых встреч.',
    colors: ['черный', 'коричневый'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    inStock: true,
    tags: ['туфли', 'классические', 'натуральная кожа', 'деловые'],
  },
  {
    id: 'shoes_m_sneakers_001',
    name: 'Мужские кроссовки',
    category: 'shoes',
    subcategory: 'sneakers',
    gender: 'men',
    price: 5200,
    description: 'Стильные мужские кроссовки для спорта и повседневной носки.',
    colors: ['черный', 'белый', 'серый', 'темно-синий'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    inStock: true,
    tags: ['кроссовки', 'стильные', 'спорт', 'повседневные'],
  },
  {
    id: 'shoes_m_boots_001',
    name: 'Мужские ботинки',
    category: 'shoes',
    subcategory: 'boots',
    gender: 'men',
    price: 7800,
    description: 'Прочные мужские ботинки из нубука с протектором.',
    colors: ['коричневый', 'черный'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    inStock: true,
    tags: ['ботинки', 'прочные', 'нубук', 'протектор'],
  },
  {
    id: 'shoes_m_loafers_001',
    name: 'Мужские лоферы',
    category: 'shoes',
    subcategory: 'loafers',
    gender: 'men',
    price: 6200,
    description: 'Комфортные мужские лоферы из мягкой кожи.',
    colors: ['коричневый', 'черный', 'темно-синий'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    inStock: true,
    tags: ['лоферы', 'комфортные', 'мягкая кожа', 'повседневные'],
  },

  // Нижнее белье
  {
    id: 'underwear_w_bra_001',
    name: 'Кружевной бюстгальтер',
    category: 'underwear',
    subcategory: 'bra',
    gender: 'women',
    price: 2800,
    description: 'Элегантный кружевной бюстгальтер с мягкими чашечками.',
    colors: ['черный', 'белый', 'бежевый', 'красный'],
    sizes: ['70B', '70C', '75B', '75C', '80B', '80C'],
    inStock: true,
    tags: ['бюстгальтер', 'кружевной', 'мягкие чашечки', 'элегантный'],
  },
  {
    id: 'underwear_w_panties_001',
    name: 'Трусики слип',
    category: 'underwear',
    subcategory: 'panties',
    gender: 'women',
    price: 1200,
    description: 'Комфортные женские трусики из хлопка с кружевной отделкой.',
    colors: ['черный', 'белый', 'бежевый', 'розовый'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tags: ['трусики', 'слип', 'хлопок', 'кружевная отделка'],
  },
  {
    id: 'underwear_w_set_001',
    name: 'Комплект белья',
    category: 'underwear',
    subcategory: 'set',
    gender: 'women',
    price: 3800,
    description: 'Изысканный комплект из бюстгальтера и трусиков с вышивкой.',
    colors: ['черный', 'красный', 'белый'],
    sizes: ['70B', '70C', '75B', '75C', '80B', '80C'],
    inStock: true,
    tags: ['комплект', 'бюстгальтер', 'трусики', 'вышивка'],
  },
  {
    id: 'underwear_w_thermal_001',
    name: 'Термобелье женское',
    category: 'underwear',
    subcategory: 'thermal',
    gender: 'women',
    price: 2200,
    description: 'Теплое термобелье из мериносовой шерсти для холодного времени года.',
    colors: ['серый', 'черный', 'белый'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    inStock: true,
    tags: ['термобелье', 'мериносовая шерсть', 'теплое', 'зимнее'],
  },
  {
    id: 'underwear_m_boxers_001',
    name: 'Мужские трусы-боксеры',
    category: 'underwear',
    subcategory: 'boxers',
    gender: 'men',
    price: 1600,
    description: 'Комфортные мужские трусы-боксеры из хлопка с эластаном.',
    colors: ['черный', 'серый', 'темно-синий', 'белый'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['трусы-боксеры', 'хлопок', 'эластан', 'комфортные'],
  },
  {
    id: 'underwear_m_briefs_001',
    name: 'Классические трусы',
    category: 'underwear',
    subcategory: 'briefs',
    gender: 'men',
    price: 1200,
    description: 'Классические мужские трусы из натурального хлопка.',
    colors: ['белый', 'черный', 'серый'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['трусы', 'классические', 'натуральный хлопок', 'базовые'],
  },
  {
    id: 'underwear_m_undershirt_001',
    name: 'Мужская майка',
    category: 'underwear',
    subcategory: 'undershirt',
    gender: 'men',
    price: 980,
    description: 'Базовая мужская майка из мягкого хлопка.',
    colors: ['белый', 'серый', 'черный'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['майка', 'базовая', 'мягкий хлопок', 'нижнее белье'],
  },
  {
    id: 'underwear_m_thermal_001',
    name: 'Термобелье мужское',
    category: 'underwear',
    subcategory: 'thermal',
    gender: 'men',
    price: 2800,
    description: 'Мужское термобелье с влагоотводящими свойствами для активного отдыха.',
    colors: ['черный', 'серый', 'темно-синий'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    inStock: true,
    tags: ['термобелье', 'влагоотводящее', 'активный отдых', 'спортивное'],
  },
];
